# Generated by Django 5.1.6 on 2025-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance_app', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
