# Generated by Django 5.1.6 on 2025-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance_app', '0004_alter_products_price_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('new_password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
            ],
        ),
    ]
