# Generated by Django 5.1.6 on 2025-02-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance_app', '0005_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='confirm_password',
            new_name='password',
        ),
    ]
