# Generated by Django 5.1.6 on 2025-02-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance_app', '0006_rename_confirm_password_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='new_password',
        ),
    ]
