# Generated by Django 5.1.6 on 2025-02-12 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance_app', '0008_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 18, 1, 6, 602516, tzinfo=datetime.timezone.utc)),
        ),
    ]
