# Generated by Django 5.1.6 on 2025-02-20 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance_app', '0009_alter_orderhistory_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
